# ~/.config/hypr/hyprlock.conf

# ============================================================
# General
# ============================================================

general {
    hide_cursor = false
    ignore_empty_input = true
}

# ============================================================
# Background
# ============================================================

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}


# ============================================================
# Image
# ============================================================
image {
    monitor =
    path = /home/$USER/.config/hypr/hyprlock-image.png
    size = 500
    rounding = 0 # no rounding
    border_size = 0

    position = 0, -130
    halign = center
    valign = top
    zindex = 0
}

# ============================================================
# Input field
# ============================================================

input-field {
    monitor =
    size = 300, 60
    position = 0, -880
    halign = center
    valign = top

    inner_color = rgba(17, 17, 27, 0.15)
    outer_color = rgba(137, 180, 250, 1)
    outline_thickness = 2

    font_color = rgb(89dceb)

    fade_on_empty = false
    placeholder_text = <i>Authorised Personal Only...</i>

    rounding = 12
    check_color = rgb(fab387)
    fail_color = rgb(f38ba8)

    fail_text = <i>$FAIL: <b>$ATTEMPTS</b></i>
    capslock_color = rgb(ffff00)

    hide_input = false
}

# ============================================================
# Time
# ============================================================

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgb(74c7ec)

    font_size = 30
    font_family = JetbrainsMono Nerdfont

    position = 0, -20
    halign = center
    valign = top
}

# ============================================================
# Date
# ============================================================

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    color = rgb(74c7ec)

    font_size = 22
    font_family = JetbrainsMono Nerdfont

    position = 0, -80
    halign = center
    valign = top
}

# ============================================================
# Keyboard Layout
# ============================================================

label {
    monitor =
    text =    $LAYOUT
    color = rgb(74c7ec)

    font_size = 16
    font_family = JetbrainsMono Nerdfont

    position = 10, 30
    halign = left
    valign = bottom
}

# ============================================================
# Lock indicator
# ============================================================

label {
    monitor =
    text = 🔒
    color = rgba(255, 255, 255, 0.6)

    font_size = 20

    position = 30, -30
    halign = left
    valign = top
}
