import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
	program = "/bin/fish"

[env]
    TERM = "xterm-256color"

[window]
    startup_mode = "Maximized"
    blur = true

[font]
    normal = {family = "JetBrainsMono Nerd Font", style = "bold"}
    size = 10

[cursor]
    style = {shape = "Underline" , blinking = "On"}
    vi_mode_style = { shape = "Block", blinking = "Off"}

[mouse]
    hide_when_typing = true
    
