[env]
    TERM = "xterm-256color"

[window]
    startup_mode = "Maximized"
    blur = true
    decorations = "Transparent" 
    opacity = 0.85

[font]
    normal = {family = "JetBrainsMono Nerd Font", style = "bold"}
    size = 12

[cursor]
    style = {shape = "Underline" , blinking = "On"}
    vi_mode_style = { shape = "Block", blinking = "Off"}

[mouse]
    hide_when_typing = true


[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

